apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: OPENSHIFT_NAMESPACE
  labels:
    name: SERVICE_NAME
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: DEPLOYMENT_NAME
